# Generated by Django 5.1.1 on 2024-09-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='zid_code',
            new_name='zip_code',
        ),
    ]
